#!/usr/bin/env bash
#
# bench/run.sh — build and benchmark the scalar CSR SpGEMM kernels.
#
# Builds three binaries from the unified harness (selected via -DKERNEL_*),
# runs a density sweep under qemu-riscv64, and writes all output to
# bench/results.txt.
#
# Usage:  ./bench/run.sh
#
set -euo pipefail

# Resolve repo root relative to this script, so it runs from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

CC=riscv64-linux-gnu-gcc
CFLAGS="-O3 -march=rv64gc -static -Iinclude"
HARNESS="bench/bench_csr_spgemm.c"
KDIR="src/kernels/spgemm"
RESULTS="bench/results.txt"

# Matrix sweep: fixed dims, varied density.
DIMS="256 256 256"
DENSITIES="0.01 0.05 0.10"
REPS=20

echo "Building..."
$CC $CFLAGS -DKERNEL_F32     "$HARNESS" "$KDIR/csr_scalar_f32.c"         -o bench_f32
$CC $CFLAGS -DKERNEL_UNROLL4 "$HARNESS" "$KDIR/csr_scalar_unroll4_f32.c" -o bench_unroll4
$CC $CFLAGS -DKERNEL_I8      "$HARNESS" "$KDIR/csr_scalar_i8.c"          -o bench_i8

echo "Running sweep -> $RESULTS"
{
    echo "# rv-sparse scalar SpGEMM benchmark results"
    echo "# generated by bench/run.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# compiler: $($CC --version | head -1)"
    echo "# flags: $CFLAGS"
    echo "# sweep: dims=$DIMS densities=[$DENSITIES] reps=$REPS"
    echo
    for bin in bench_f32 bench_unroll4 bench_i8; do
        for d in $DENSITIES; do
            qemu-riscv64 ./$bin $DIMS "$d" "$REPS"
        done
    done
} 2>&1 | tee "$RESULTS"

echo "Done. Results in $RESULTS"